import = [
    "~/.config/alacritty/themes/alacritty-themes/themes/tokyo-night.toml",
    "~/.config/alacritty/keybinds.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach -t 'ðŸš€ copium ï£¿' || tmux new -s 'ðŸš€ copium ï£¿'"]

[window]
dimensions = { columns = 187, lines = 42 }
dynamic_padding = true
decorations = "Buttonless"
resize_increments = true
dynamic_title = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15
builtin_box_drawing = true

[selection]
save_to_clipboard = true
